/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ComPup: typeof import('./src/components/comPup/comPup.vue')['default']
    Foot: typeof import('./src/components/foot/foot.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TokenBox: typeof import('./src/components/tokenBox/tokenBox.vue')['default']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
